server:
  port: 9000
spring:
  application:
    name: springboot-baor-week2-zuul #指定服务名
zuul:
  # prefix: / # 添加路由前缀
  prefix: /zhaofengyi.com # 添加路由前缀
  routes:
    yyx-consumers: # 这里是路由id，不能随意写
      path: /zhaofengyi-servers/** # 这里是映射路径
      url: http://127.0.0.1:8092 # 映射路径对应的实际url地址
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1